"""Changed the table name to movies

Revision ID: 9bc692d537c2
Revises: 5208692d740d
Create Date: 2023-04-10 15:23:39.830799

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bc692d537c2'
down_revision = '5208692d740d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=False),
    sa.Column('poster', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_movies_title'), ['title'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_title')

    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('poster', sa.VARCHAR(length=80), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_title', ['title'], unique=False)

    with op.batch_alter_table('movies', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_movies_title'))

    op.drop_table('movies')
    # ### end Alembic commands ###
